#pragma once

//WINDOW SETTINGS
#define SCREEN_WIDTH 1080
#define SCREEN_HEIGHT 600

#define SPLASH_STATE_SHOW_TIME 3.0

//BACKGROUND STATES
#define SPLASH_SCENE_BACKGROUND_FILEPATH "res/BACKGROUND_INIT_STATE.PNG"
#define MAIN_MENU_BACKGROUND_FILEPATH "res/BACKGROUND_MAINMENU_STATE.PNG"
#define GAME_STATE_BACKGROUND_FILEPATH "res/BACKGROUND_GAME_STATE.PNG"
#define RULES_STATE_BACKGROUND_FILEPATH "res/BACKGROUND_RULES_STATE.PNG" 

//MENU STATE BUTTONS
#define GAME_TITLE_FILEPATH "res/GAME_TITLE.PNG"
#define QUIT_BUTTON_FILEPATH "res/QUIT_BUTTON.PNG"
#define RULES_BUTTON_FILEPATH "res/RULES_BUTTON.PNG"
#define PLAY_BUTTON_FILEPATH "res/PLAY_BUTTON.PNG"

//RULES STATE BUTTONS
#define BACK_BUTTON_FILEPATH "res/BACK_BUTTON.PNG"

//GAME STATE BUTTONS
#define PAUSE_BUTTON_FILEPATH "res/PAUSE_BUTTON.PNG"
#define START_BUTTON_FILEPATH "res/START_BUTTON.PNG"
#define PLUS_BUTTON_FILEPATH "res/PLUS_BUTTON.PNG"
#define MINUS_BUTTON_FILEPATH "res/MINUS_BUTTON.PNG"
#define CLEAN_BUTTON_FILEPATH "res/CLEAN_BUTTON.PNG"
#define RANDOMIZE_BUTTON_FILEPATH "res/RANDOMIZE_BUTTON.PNG"





